### ISSUE TITLE
SMTCoq was not able to check the proof certificate by zchaff

### ISSUE THREAD

**Issue by siraben** [smtcoq/smtcoq#106]
Going through the examples in the tutorial, it appears that SMTCoq fails to check the proof certificate returned by zchaff.

The version of zchaff is 2004.5.13. I tried using the 2007.3.12 version but I get a different unrelated error.

### To reproduce
File `Test.v`
```coq
Require Import SMTCoq.SMTCoq.
Require Import Bool.                                 
Require Import ZArith.                               

Goal forall a b c,
  (a || b || c) && ((negb a) || (negb b) || (negb c)) && ((negb a) || b) && ((negb b) || c) && ((negb c) || a) = false.
Proof.
  Fail zchaff.
Abort.

Goal forall (i j k : Z),
    let a := Z.eqb i j in
    let b := Z.eqb j k in
    let c := Z.eqb k i in
  (a || b || c) && ((negb a) || (negb b) || (negb c)) && ((negb a) || b) && ((negb b) || c) && ((negb c) || a) = false.
Proof.
  zchaff.
Qed.
```

```ShellSession
$ docker run -v "$(pwd):$(pwd)" -w "$(pwd)" -it nixos/nix nix-shell -p bash
$ nix-shell -E 'with import (builtins.fetchTarball "https://github.com/NixOS/nixpkgs/archive/9527fa83ad3ceda3905916b8a2ac5dc7d00904f5.tar.gz") {}; mkShell { buildInputs = [ cvc5 coq_8_13 coqPackages_8_13.smtcoq zchaff ]; }'
$ coqtop -l test.v
```

**Comment by ckeller** [comment]
Hi @siraben 
Did you follow the [installation instructions](https://github.com/smtcoq/smtcoq/blob/coq-8.13/INSTALL.md#zchaff) ? In particular, proof production must be turned on before compiling ZChaff.

**Comment by siraben** [comment]
@ckeller at the time I didn't enable proof production but I tried it out [here](https://github.com/siraben/nixpkgs/commit/54c3a764423160403d5e62db7d2de9d12fb80f33) and I still get the same error. Are you able to replicate it?

**Comment by ckeller** [comment]
@siraben with your patch, I do not get any error. I run it using:
```
docker run -v "$(pwd):$(pwd)" -w "$(pwd)" -it nixos/nix nix-shell -p bash
nix-shell -E 'with import (builtins.fetchTarball "https://github.com/siraben/nixpkgs/archive/54c3a764423160403d5e62db7d2de9d12fb80f33.tar.gz") {}; mkShell { buildInputs = [ coq_8_13 coqPackages_8_13.smtcoq zchaff ]; }'
coqtop -l test.v
```

**Comment by siraben** [comment]
@ckeller the first zchaff command should fail. If the file ran that means the first zchaff did indeed fail (see the error by removing `Fail`)

**Comment by ckeller** [comment]
@siraben Indeed, sorry about that... I investigated and it appears that the certificate produced by this version of ZChaff is not valid. Would it be possible to make nix use the latest version?

**Comment by siraben** [comment]
@ckeller still fails on commit f36bf11e994cc269c2ec92b061b082e3516f472f as well, or did you mean the version of zchaff used?

**Comment by siraben** [comment]
Ok, so using the latest commit of SMTCoq f36bf11e994cc269c2ec92b061b082e3516f472f and version 2007.3.12 of zchaff, the proof certificate check succeeds.
