### ISSUE TITLE
Checker for VeriT failing with following SMT2 file

### ISSUE THREAD

**Issue by ymherklotz** [smtcoq/smtcoq#110]
Hi, the following SMT2 file seems to fail with the extracted SMT checker in [/src/extraction](https://github.com/smtcoq/smtcoq/tree/coq-8.13/src/extraction), although I think that it should be supported and valid.  Unfortunately it is relatively large and not the easiest to reduce into a smaller test-case, sorry about that.  I will try to get a smaller test-case, but every similar SMT2 file passes through the checker fine.  I mainly rely on multiple `ite` assertions with some linear arithmetic.

The SMT2 file and the proof is attached in [verit.zip](https://github.com/smtcoq/smtcoq/files/9439998/verit.zip) and also added them in a [gist here](https://gist.github.com/ymherklotz/e1c50362518c03dc999c0e5e1a1029e7).  It mainly relies on transitivity, congruence and Lia.

It should be possible to reproduce the proof using the following:

```shell
veriT --proof-prune --proof-merge --proof-with-sharing --cnf-definitional \
      --disable-ackermann --input=smtlib2 --proof=file.log file.smt2 
```

Then, I ran the check using:

```shell
./smtcoq file.smt2 file.log
```

Which produces the following output:

```shell
Calling the veriT verifier on file.smt2 and file.log...
The verifier failed to check the trace :-(
```

Please let me know if you think it's a mistake with my input or if you think this may be an issue with the checker or maybe with the veriT proof generation. Let me know if there is anything else I can add.

**Comment by ckeller** [comment]
Hi @ymherklotz 
Thanks for reporting. After investigation, it appears that veriT output an invalid certificate. Indeed, on line 73, it is resolving twice the same clause (number 72), which is incorrect. When removing one of the two 72, the certificate goes through. Never saw it in years of using this version of veriT...
This may already be patched in the last version of veriT, but SMTCoq currently does not support it. @arjunvish is implementing the port to the new proof certificate format.
Sorry about it...

**Comment by ymherklotz** [comment]
Hi @ckeller, thanks so much for looking into it and debugging it.  That makes sense, I hadn't noticed that 72 was duplicated. Any variations on the input and even a slightly different but equivalent formulation seems to not produce the bug, so that works for me for now.
