### ISSUE TITLE
Adding support for coq 8.16

### ISSUE THREAD

**Issue by volodeyka** [smtcoq/smtcoq#112]
Hello! We want to use SMTCoq in our project, but in order to do it, we need SMTCoq to support a newer Coq versions. Could you please tell me if you are going to support Coq >= 8.15?

**Comment by ckeller** [comment]
Hi @volodeyka 
It is the perfect timing to ask: I am currently pushing towards recent version of Coq. SMTCoq is now available for Coq-8.14 and hopefully it will be for Coq-8.15 very soon.
May I ask what you would like to use from SMTCoq?

**Comment by volodeyka** [comment]
Cool! We are looking forward!
Do not want to spam here with the full context, but at some point, in our project we have proof obligations, validity of which was checked with z3. And we want to use SMTCoq and other coq automation tools in order to dispatch those goals.

**Comment by ckeller** [comment]
Hi
The port is done! You can easily install SMTCoq by adding extra-dev to opam: `opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev` (or doing `opam update` if it is already added), then `opam install coq-smtcoq`.
I have seen that you have joined the SMTCoq forum, feel free if you have questions or comments!

**Comment by volodeyka** [comment]
Thank you!
