### ISSUE TITLE
Installation with opam failed, reference verit_bool_base was not found in the current # environment

### ISSUE THREAD

**Issue by REA1** [smtcoq/smtcoq#120]
I followed the INSTALL.md and tried installing 2.0 with opam. The compilation failed for the error 
"reference verit_bool_base was not found in the current # environment" in "Tactics.v".

Here is the error message from opam:
```
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
⬇ retrieved coq-smtcoq.2.0+8.13  (cached)
[ERROR] The compilation of coq-smtcoq.2.0+8.13 failed at "make -j7".

#=== ERROR while compiling coq-smtcoq.2.0+8.13 ================================#
# context     2.1.4 | linux/x86_64 | ocaml-base-compiler.4.09.0 | https://coq.inria.fr/opam/released#2023-04-20 18:40
# path        ~/.opam/ocaml-base-compiler.4.09.0/.opam-switch/build/coq-smtcoq.2.0+8.13
# command     ~/.opam/opam-init/hooks/sandbox.sh build make -j7
# exit-code   2
# env-file    ~/.opam/log/coq-smtcoq-307834-167cc9.env
# output-file ~/.opam/log/coq-smtcoq-307834-167cc9.out
### output ###
# [...]
# File "./Trace.v", line 23, characters 0-16:
# Warning: There is no flag or option with this name: "Vm Optimize".
# [unknown-option,option]
# COQC Tactics.v
# File "./Tactics.v", line 72, characters 52-67:
# Error: The reference verit_bool_base was not found in the current
# environment.
# 
# make[2]: *** [Makefile:720: Tactics.vo] Error 1
# make[1]: *** [Makefile:343: all] Error 2
``` 

The versions in the opam switch
- ocaml-base-compiler.4.09.0
- coq 8.13.2

As one who's still new to Latc, it turns out that the error message actually seemed reasonable to me as I explored other parts of the code and couldn't find "verit_bool_base" elsewhere. I'm pretty curious about where "verit_bool_base" actually comes from.

**Comment by ckeller** [comment]
Hi @REA1 
`verit_bool_base` is a tactic written in OCaml: https://github.com/smtcoq/smtcoq/blob/coq-8.13/src/g_smtcoq.mlg#L116
You may be running into the same bug as #117 (which I am sorry, I did not finish to merge yet, but I can do it next week): which version of GNU make do you have?

**Comment by REA1** [comment]
@ckeller Ahh, got it. Thank you!

```
$ make --version
```
gives me
```
GNU Make 4.4.1
...
```
The problem is probably the same as #117.

**Comment by ckeller** [comment]
@REA1 #117 has been merged in the development version of SMTCoq, you can check if it solves your problem and close the issue.
To install the development version of SMTCoq, you can follow [these instructions](https://github.com/smtcoq/smtcoq/blob/coq-8.13/INSTALL.md#installation-of-the-development-version-via-opam).

**Comment by REA1** [comment]
Version dev+8.13 installed successfully.
