### ISSUE TITLE
Use of modular_constr_pr in src/trace/smtMisc.ml

### ISSUE THREAD

**Issue by herbelin** [smtcoq/smtcoq#126]
Hi, a Coq PR (namely coq/coq#17875) modified the type of `Ppconstr.modular_constr_pr` resulting in an incompatibility in `SmtMisc.string_coq_constr`. Are there any reasons why the code of `string_coq_constr` uses `Ppconstr.modular_constr_pr`  rather than `Ppconstr.pr_constr_expr` which is less tricky? Is it to be sure that the the original copy of `Ppconstr.pr_constr_expr` will not be overriden (since it is part of a record which can be overriden)? If yes, since a change is anyway needed, would that help that Coq export the original copy of `Ppconstr.pr_constr_expr` (ensured not to be overriden)?

**Comment by ckeller** [comment]
Hi @herbelin , there is no particular reason so I think it is fine to make the change.

**Comment by herbelin** [comment]
OK, then I did PR #127 to instead use the more standard `Ppconstr.pr_constr_expr`. I chose the already-exported overridable version since you seem to say that it does not matter particularly. Thanks for the reply.

**Comment by herbelin** [comment]
I did not see that Pierre had already a fix. Sorry for the noise, closing.

**Comment by ckeller** [comment]
No problem, thanks to both of you!
