### ISSUE TITLE
Sign and zero extension seem to be incorrectly implemented

### ISSUE THREAD

**Issue by pwilke** [smtcoq/smtcoq#139]
Hello,

There seems to be an inconsistency in the way bitvectors are represented.

The addition function ([`bv_add`](https://github.com/smtcoq/smtcoq/blob/coq-8.18/src/bva/BVList.v#L563)) seems to treat the list of booleans as little-endian, i.e. the least significant bits are at the head of the list.

However, the sign- and zero-extensions treat the list as if it were encoded in big-endian (most significant bit first).
In particular, the [`sextend`](https://github.com/smtcoq/smtcoq/blob/coq-8.18/src/bva/BVList.v#L2299) function gets the bit to repeat (should be the MSB) from the head of the list.
Moreover, the extend function adds bits at the head of the list (so new least significant bits) where it should add bits at the end.

**Comment by ckeller** [comment]
Thanks for reporting! I will propose a fix soon.

**Comment by pwilke** [comment]
I've started to fix the implementation and  would be happy to contribute. 
Just to be sure, the correct representation is little-endian, right?

**Comment by ckeller** [comment]
Thanks, I also started :-) Actually, there is a lot to improve in the library.
Indeed, we will stick to little endian.
