### ISSUE TITLE
Makefile.conf of standard version contains hard-coded paths

### ISSUE THREAD

**Issue by vblot** [smtcoq/smtcoq#37]
The file `Makefile.conf` contains hard-coded paths to executables:
```
COQMF_OCAMLFIND=/usr/bin/ocamlfind
COQMF_CAMLP4=camlp5
COQMF_CAMLP4O=/usr/bin/camlp5o
COQMF_CAMLP4BIN=/usr/bin/
COQMF_CAMLP4LIB=/usr/lib/ocaml/camlp5

```
which prevents building from e.g. an opam-installed ocaml.

Re-running instructions listed in `Make` allows to rebuild a `Makefile.conf` with the paths of the local machine (but still hard-coded).

**Comment by ckeller** [comment]
Thanks for reporting!
I have changed the way the Makefile is generated; @vblot can you confirm that it works?
