### ISSUE TITLE
Broken tactic verit with coq 8.7.2

### ISSUE THREAD

**Issue by vblot** [smtcoq/smtcoq#38]
With coq 8.7.2, tactic verit throws:
```
In nested Ltac calls to "verit" and "h", last term evaluation failed.
Error: Variable h should be bound to a term.
```
for example in `example/Example.v`.

**Comment by ckeller** [comment]
Thanks for the report.
I know, but this bug shows up only with native-coq.
Tactics are currently broken with native-coq and I do not plan to fix them as people are more likely to use standard Coq for tactics.

**Comment by vblot** [comment]
Indeed it doesn't happen with standard coq. If tactics with native-coq are unsupported then I think it should be written in README or INSTALL, or there should be a warning when one tries to use them.

Btw, Conversion_tactics doesn't work anymore with native-coq since the change from appcontext to context (but indeed appcontext doesn't work anymore with the latest versions of coq).

**Comment by ckeller** [comment]
Thanks; I added warnings in the Makefile.

@vblot : Do you think we can simply remove the tactics in the native version (in which case, someone who try to use one of them will get an error message stating that it does not exist), or we should keep them but output an error message?

**Comment by vblot** [comment]
I would lean towards a specific error message, like "tactics are not supported with native-coq". Otherwise with the standard coq message people may think they forgot some environment variable or something and may lose time trying to fix it.

**Comment by ckeller** [comment]
Ok thanks, I will add that before the release.
