### ISSUE TITLE
Is an opam package ok?

### ISSUE THREAD

**Issue by mattam82** [smtcoq/smtcoq#49]
Hi, I just submitted an (extra-dev) package for smtcoq on the coq opam archive, which should allow easy experimentation for users. Is it ok with you having this package (opam users will just have to explicitely add the development repo  http://coq.inria.fr/opam/extra-dev to get access to smtcoq) ? If so, can you have a look at the package description there? https://github.com/coq/opam-coq-archive/pull/872

**Comment by gmalecha** [comment]
An opam package would be *extremely* useful.

**Comment by ckeller** [comment]
Hi @gmalecha 
I forgot to close this issue but there is an opam package, in the extra-dev repo.
