### ISSUE TITLE
Exception Axiom_form_unsupported whenever I use the smt tactic

### ISSUE THREAD

**Issue by stevenvar** [smtcoq/smtcoq#56]
Hi,

I seem to have an issue with my install of smtcoq.

I used opam and installed it with ocaml 4.09.0 and coq 8.9.0. 

I cannot make the example of the project page work :

```ocaml
Lemma identity' :
    forall a, (op a e = a).
  Proof. smt. Qed.
```

Gives me back an error:

```
Ltac call to "smt (constr_list)" failed.
Anomaly
"Uncaught exception Smtcoq_plugin.SmtCommands.Axiom_form_unsupported."
```

Help?

**Comment by ckeller** [comment]
Hi @stevenvar 
Did you install the recommended version of CVC4 <https://github.com/smtcoq/smtcoq/blob/master/INSTALL.md#CVC4>?

**Comment by stevenvar** [comment]
I think so: 

```
$ cvc4 --version
This is CVC4 version 1.6
```

**Comment by ckeller** [comment]
Hi @stevenvar 
Really sorry for the delay.
Thank you for reporting, it was indeed an error on the webpage. My bad: I tried to minimize the example and it was not working anymore. The correct version was in the `example/Example.v` file.
Sorry for the inconvenience.
