### ISSUE TITLE
InsertionSort example library import fails

### ISSUE THREAD

**Issue by ecranceMERCE** [smtcoq/smtcoq#57]
Hello,
I have installed SMTCoq through `opam` as well as the three provers CVC4, veriT, and zChaff, as explained in the `INSTALL.md` file. However, it looks like I need to import the `SMTCoq.SMTCoq` module instead of `SMTCoq`. Executing `coqc Example.v` with this modification works (veriT shows warnings but the proofs work in Coq), but the following line in `InsertionSort.v` leads to an error locating the library:

https://github.com/smtcoq/smtcoq/blob/7ad0aff65751133b298ef41861ed8cd688cf18eb/examples/InsertionSort.v#L28

When commenting this line and changing the import to `SMTCoq.SMTCoq`, the `coqc` command still fails not recognising the `-->` symbol introduced in the library. I may have missed some instructions in `INSTALL.md`. Do you have any idea regarding this module issue?

Thanks in advance.

**Comment by ckeller** [comment]
Thank you for reporting! You were completely right, I did not update this example for a while. Everything is now fixed.
