### ISSUE TITLE
veriT failed with the error: Invalid memory reference

### ISSUE THREAD

**Issue by PoisonReverse** [smtcoq/smtcoq#64]
I'm trying to run the examples found in Example.v that use the verit tactic. However, every time I use the verit tactic or the verit_bool tactic, I get

```
Error:
In nested Ltac calls to "verit (constr_list)", "verit_bool (constr_list)" and
"verit_bool_base (constr_list)", last call failed.
veriT failed with the error: Invalid memory reference
```

I saw that there was a similar issue here : 
https://github.com/smtcoq/smtcoq/issues/45#issuecomment-481691803

But I'm not sure if it's an issue that is ongoing or if it is fixed or if I may be doing something wrong?

I did not add the following lines to my .v file that were in Example.v

```
Section Verit.
  Verit_Checker "XXXX.smt2" "XXXX.vtlog".
End Verit.
```

because it seems like the .smt2 and .vtlog files are generated after compiling my .v file. This is the command that is outputted after I compile.

```
veriT --proof-prune --proof-merge --proof-with-sharing --cnf-definitional --disable-ackermann --input=smtlib2 --proof=/var/folders/q9/r697fvcs5vn6z7p9fzlzf18m0000gn/T/verit_coq49e927.vtlog /var/folders/q9/r697fvcs5vn6z7p9fzlzf18m0000gn/T/verit_coq49e927.smt2 2> /var/folders/q9/r697fvcs5vn6z7p9fzlzf18m0000gn/T/warnings_veritf12b5b.log
```

Is the .smt2 file and .vtlog file supposed to be added to the .v file before compiling it? Or do I use the .vtlog and .smt2 files that are generated from compilation?

**Comment by ckeller** [comment]
Hi @PoisonReverse 
This problem is likely due to the fact that veriT does not distinguish between warnings and errors, and I thus report as an error something which is a warning. Can you try with the new commit in master?

**Comment by PoisonReverse** [comment]
Oh I see, that is the intended behavior. The 'Invalid memory reference' error is showing up as a warning now, after I tried the latest version. Thanks for the clarification. 
If I had other questions relating to how to interpret the results of SMTCoq or how to do something with SMTCoq, would I submit it as an issue or is there a separate forum to discuss these things?

**Comment by ckeller** [comment]
There is no forum yet, I guess an issue is currently the best :-)
