### ISSUE TITLE
Clarify axiom usage?

### ISSUE THREAD

**Issue by andres-erbsen** [smtcoq/smtcoq#71]
Hi,

I read in [`BEST_PRACTICE.md`](https://github.com/smtcoq/smtcoq/blob/632b7b11b25f78461872f50621b325321678810c/src/BEST_PRACTICE.md#axioms):

> No axiom should be added. No library adding axioms should be imported (except Int63 and Array).

However, it [seems](https://github.com/smtcoq/smtcoq/search?l=Coq&q=Axiom) that there are quite a few axioms currently in the repository beyond the requisite classical assumptions. It looks like the examples depend on them as well https://github.com/andres-erbsen/smtcoq/compare/link-num-correctly...andres-erbsen:show-print-assumptions .

So, what's up with that? Are they just TODOs, to be proven when somebody gets around to it, or are some of them intended to serve as golden models of theories?

Thanks,
Andres

**Comment by ckeller** [comment]
Hi @andres-erbsen 
- Axioms in `src/versions/standard/Int63/Int63Axioms_standard.v` and `src/versions/standard/Array/PArray_standard.v` are Int63 and Array axioms authorized in the best practice. They will remain. They are required to use [native data structures](https://coq.github.io/doc/v8.10/refman/language/gallina-extensions.html#primitive-integers).
- "Axioms" in `src/Conversion_tactics.v` are inside a module signature, they are not axioms.
- Axioms in `src/bva/BVList.v`, `src/cnf/Cnf.v`, `src/array/Array_checker.v` and `src/bva/Bva_checker.v`, as well as classical axioms, are badly introduced axioms, it is on the [task list](https://github.com/smtcoq/smtcoq/issues/40) to remove them. I can make it a priority if you require.

**Comment by andres-erbsen** [comment]
Ok. Just to make sure I understand correctly, here are answers to how I asked the questions:

0. none of the axioms are "golden models" of smt theories (good)
1. there are TODOs, they are on the TODO list.
2. there are axioms modeling the native-coq data structures for ocaml integers and arrays; the checker uses these data structures so its proof relies on the axioms. This is the category that the note in the best practices file refers to.

After looking through the `Print Assumptions` output with this in mind, I think there also is a third class:

3. There are stand-in implementations for these data structures written in standard Coq. The same axioms are declared for these implementations so that `configure` magic makes the same checker code build either way.

This last class is different from the previous because properties of data structures implemented inside Coq should be provable inside Coq, and yet they are admitted. I get that they are not fun to prove -- [been there, done that](https://github.com/mit-plv/coqutil/pull/26#issuecomment-617162085). However, two implementations being interchangeable in practice does not mean that the same axioms hold about them. A quick skim through the admitted properties reveals the following oopsie, which would also have been found by a "crush" tactic heuristically specializing `get_ext`:

```
Require Import SMTCoq.versions.standard.Array.PArray.
Goal False.
  pose proof get_ext _ (set (make 1 0) 0 0) (make 1 0) eq_refl
    (fun i _ => ltac:(cbn; destruct(IntOrderedType.compare i 0%int); trivial))
    eq_refl;
  discriminate.
Qed.
```

It seems that one path out of awkwardness with this last category would be to drop the coq-defined (non-native) version and only use axioms declared in coq itself, except that I had been hoping to use SMTCoq *without* pulling in the native-coq data structures and associated axioms so I don't feel enthusiastic about suggesting this.

**Comment by ckeller** [comment]
Nice catch.

Actually, here is my plan. These two libraries which are currently part of SMTCoq are meant to be removed, and their use replaced by use of the true Coq libraries of native data-structures.

- Int63 is already part of Coq since version 8.10. This is actually why SMTCoq master is still on 8.9 : before basing it on 8.10 or 8.11, I want to replace this silly library by native integers. (It is also on the task list. Again, I can make it a priority if required.)
- As far as @maximedenes told me, Array should be part of Coq-8.13. In the same way, I will thus get rid of the silly library for arrays. I thus do not plan to prove the lemmas since it will soon be replaced. I may try to make it more consistant, though, as you suggest!

I understand that you would prefer not to rely on Coq native data-structures, but that would make SMTCoq more complex to maintain since I want to keep a version with them.

**Comment by ckeller** [comment]
By the way, you are most welcome to join the SMTCoq framateam for discussion: https://framateam.org/smtcoq

**Comment by ckeller** [comment]
Regarding the particular case of extensionality of arrays, it is actually not used in SMTCoq, and thus I got rid of it.

**Comment by andres-erbsen** [comment]
Thanks for your responses. Don't jump into proving boring stuff just for us quite yet -- whether or not we need to do this catch-up ourselves is unlikely to change how much we SMTCoq.
