### ISSUE TITLE
Compatibility with OCaml < 4.08 + stdlib-shims

### ISSUE THREAD

**Issue by JasonGross** [smtcoq/smtcoq#73]
SMTCoq does not build with OCaml < 4.08, as there is no Stdlib, only Pervasives.   This can be fixed with `opam install stdlib-shims`, but then we need to pass `-package stdlib-shims` to all of the ocaml invocations.

**Comment by ckeller** [comment]
Thank you for reporting. I do not plan to support older versions of OCaml, I have updated installation intructions.
