### ISSUE TITLE
Testing on OSX

### ISSUE THREAD

**Issue by mattam82** [smtcoq/smtcoq#8]
Hi, I wanted to give a try to smtcoq on OS X with cvc4 and I currently cannot make it work.
I'm trying to process this .v file:

Require Import SMTCoq.SMTCoq.
Require Import Bool.
Goal forall b, (b || b) = b.
  cvc4.

I'm using a binary of cvc4 downloaded from their website (cvc4-.1.5), using a manually compiled version of SMTCoq's lfsc branch as of today, on coq 8.6. The error I get right now is:

<prompt>Unnamed_thm < 21 |branch| 0 < </prompt>cvc4.
(set-option :print-success true)
(set-option :produce-assignments true)
(set-option :produce-proofs true)
(set-logic QF_SAT)
(declare-fun op_0 () Bool)
(assert (not (= (or op_0 op_0) op_0)))
(check-sat)
(get-proof)
Toplevel input, characters 0-4:
> cvc4.
> ^^^^
In nested Ltac calls to "cvc4" and "cvc4_bool", last call
failed.
System error: "/Volumes/Dev/coq/scratch/sat.plf: No such file or directory"

If I run cvc4 --lang smt and send the same commands I get positive feedback though, (check-sat) results in "unsat" and (get-proof) gives me a bunch of commands.

**Comment by ckeller** [comment]
Hi Matthieu
Did you follow the instructions in the paragraph "Setting up environment for SMTCoq" in the [installation instructions](https://github.com/smtcoq/smtcoq/blob/lfsc/INSTALL.md) ?

**Comment by ckeller** [comment]
The current version of SMTCoq is working on MacOS. Closing this issue.
