### ISSUE TITLE
Coq 8.13

### ISSUE THREAD

**Issue by liyishuai** [smtcoq/smtcoq#88]
On `master` branch, under `/src` directory, `./configure.sh` failed with:
> camlp5 macro files not supported anymore, please port g_smtcoq.ml4 to coqpp

Environment:
- Coq 8.13.1
- OCaml 4.10.2
- macOS 11.2.3

**Comment by ckeller** [comment]
Hello
It is already on the TODO list to port to more recent version of Coq.
Currently, you can use Coq 8.9 (`master` branch), 8.10 (`v8.10` branch) or 8.11 (`v8.11` branch).

**Comment by ckeller** [comment]
SMTCoq is now ported to Coq-8.13
It is available in the [coq-8.13 branch](https://github.com/smtcoq/smtcoq/tree/coq-8.13), and via opam as soon as [this pull request](https://github.com/coq/opam-coq-archive/pull/1734) is merged.
