### ISSUE TITLE
../plugins/micromega: No such file or directory

### ISSUE THREAD

**Issue by jimyu94** [smtcoq/smtcoq#9]
Hi! I tried to compile from your source, but I got the error shown in the title. Where is the micromega package? Thanks!

**Comment by jimyu94** [comment]
I am using Coq 8.7.1, but this should be irrelevant to this problem.

**Comment by ckeller** [comment]
Hi
Unfortunately, smtcoq is not ported to Coq 8.7 yet. I may have a look at it in the next weeks.

**Comment by ckeller** [comment]
SMTCoq is now ported to Coq-8.7 and all the more recent versions of Coq.
